#!/usr/bin/env python3
"""Regression checks that qualification protects honest observation without becoming a semantic rules engine."""
from pathlib import Path
import sys,tempfile
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'qualification'))
from integrity import artifact_similarity_flags,checkpoint_chain_contiguous,event_specific_ref_paths,exact_duplicate_artifact_flags,run_control_flags


def req(cond,msg):
    if not cond:raise AssertionError(msg)


def main():
    with tempfile.TemporaryDirectory(prefix='aura-qualification-integrity-') as td:
        root=Path(td);ws=root/'workspace';ws.mkdir();p=ws/'attachments'/'field.json';p.parent.mkdir(parents=True);p.write_text('new evidence\n');before={'workspace':{'files':[]}};after={'workspace':{'digest':'after','files':[{'path':'attachments\\field.json','sha256':'abc'}]}}
        req(event_specific_ref_paths(['attachments/field.json'],before,after,ws),'new event evidence must be auditable as event-specific');req(not event_specific_ref_paths(['attachments/field.json'],{'workspace':{'files':[{'path':'attachments/field.json','sha256':'abc'}]}},after,ws),'unchanged prior evidence must not count as event-specific');req(checkpoint_chain_contiguous({'workspace':{'digest':'same'}},{'workspace':{'digest':'same'}}),'adjacent evaluator checkpoints should remain auditable')
        a=root/'a.md';b=root/'b.md';body='# Deliverable\n\nGeneric operational guidance for the target audience.\n'*12;a.write_text(body);b.write_text(body)
        flags=artifact_similarity_flags([{'event_id':'E1','kind':'workflow_diagnostic','workflow_id':'one','actual_artifacts':[str(a)]},{'event_id':'E2','kind':'workflow_diagnostic','workflow_id':'two','actual_artifacts':[str(b)]}],max_examples=1);req(flags.get('E1'),'highly similar distinct-job artifacts must still be surfaced for review')
        duplicate=exact_duplicate_artifact_flags([{'event_id':'E1','actual_artifacts':[str(a)]},{'event_id':'E2','actual_artifacts':[str(b)]}]);req(duplicate.get('E1') and duplicate.get('E2'),'byte-identical artifacts at distinct paths must remain an integrity failure signal')
        evolving=exact_duplicate_artifact_flags([{'event_id':'L1','actual_artifacts':[str(a)]},{'event_id':'L2','actual_artifacts':[str(a)]}]);req(not evolving,'the same durable artifact path reused across longitudinal events must not be misclassified as duplicate masquerading')
        scratch=ws/'scratch';scratch.mkdir();ordinary=scratch/'batch_work.py';ordinary.write_text("for event in events: print('complete real work')\n");ordinary_flags=run_control_flags(root,ws);req(not any(x.get('path')==str(ordinary) for x in ordinary_flags),'ordinary batch automation must not be treated as qualification manipulation')
        control_script=scratch/'qualification-control.py';control_script.write_text("for event in events:\n    print('evaluator/queue.json evaluator/judgments.json')\n");control=run_control_flags(root,ws);req(any(x.get('type')=='candidate_evaluator_spec_access' and x.get('path')==str(control_script) for x in control),'candidate access to evaluator-private material must remain visible');req(any(x.get('type')=='mass_completion_runner' and x.get('path')==str(control_script) for x in control),'looping over multiple evaluator-private surfaces should remain an integrity signal')

    for retired in ('qualification/build_suite.py','qualification/missions','qualification/cases','qualification/launch.py','tests/run_qualification_framework.py'):
        req(not (ROOT/retired).exists(),f'retired qualification system returned: {retired}')

    prepare=(ROOT/'qualification/prepare_run.py').read_text();req('build_suite' not in prepare and "ap.add_argument('--mission'" not in prepare and "ap.add_argument('--profile'" not in prepare,'preparation retained generated-suite/profile/mission machinery');req("'--case'" in prepare and "'--workflow'" in prepare,'qualification must keep realistic cases plus explicit focused Workflow diagnostics');req('diagnostics require --fixture' in prepare,'focused Workflow diagnostics must use an explicit benchmark fixture rather than heuristic routing');req('OWNER_PROFILES' not in prepare and "RUBRICS['profiles']" not in prepare,'preparation retained deterministic semantic rubric-profile routing')
    common=(ROOT/'qualification/common.py').read_text();req('fixture_for(' not in common and 'family_for(' not in common,'qualification common helpers retained Workflow-ID heuristic routing')
    evaluator=(ROOT/'qualification/evaluate_run.py').read_text();req('suite.json' not in evaluator and "suite['workflow_tests']" not in evaluator,'evaluator retained retired generated-suite dependency');req('Infer substantive requirements from the ordinary request' in evaluator,'evaluator must explicitly own semantic completeness judgment');critical=evaluator.split('critical_types=',1)[1].split(';critical_run_flags',1)[0];req("'mass_completion_runner'" not in critical,'bulk automation must not be an automatic failure when it performs real work');req('EVALUATOR-ERROR' in evaluator,'broken evaluator bookkeeping must be separated from candidate failure')
    integrity=(ROOT/'qualification/integrity.py').read_text();req('evaluator/suite.json' not in integrity and 'evaluator\\\\suite.json' not in integrity,'integrity scanner retained retired suite marker')
    rubrics=(ROOT/'qualification/rubrics/rubrics.json').read_text();req('"profiles"' not in rubrics and 'profile_descriptions' not in rubrics,'qualification rubric retained domain/profile semantic taxonomy instead of universal professional dimensions')
    for retired_phrase in ('contract-execution.json','required_subcontracts','record_contract_completion.py','structured_prepublish_refs','is_reconstructable_field_snapshot','reconstructable_field_snapshot_paths'):
        req(retired_phrase not in integrity,f'qualification integrity retained deleted execution or benchmark-shaped evidence machinery: {retired_phrase}')
    controller=(ROOT/'qualification/task_controller.py').read_text();req('matching root AURA Run' not in controller and "'material_result_observed':material_result" in controller,'controller must classify observed business results rather than execution-ledger completion');req('target SOP' not in controller and 'SOP effectiveness' not in controller,'controller retained retired SOP framing');req('candidate_response_ref' in controller and 'canonical_refs or artifact_refs or response_ref' in controller,'controller must recognize useful work delivered directly in the candidate response without requiring a file artifact')
    judge=(ROOT/'qualification/build_judge_prompt.py').read_text().lower();req('do **not** require a particular aura run' in judge,'judge must not reward an AURA Run as universal proof');req('workflow-acceptance' not in judge and 'focused workflow diagnostic' in judge,'judge retained retired Workflow-acceptance terminology');req('automation is acceptable' in judge,'judge must evaluate automated work by its real result');req('captured candidate-visible response' in judge and 'do not require file creation' in judge,'judge must evaluate conversational business output without manufacturing filesystem ceremony');req('strict claim-grounding audit' in judge and 'customer quotes/testimonials' in judge and 'unsupported named capabilities' in judge,'judge must explicitly audit outward factual claims rather than reward plausible fabricated proof')
    runner=(ROOT/'qualification/run_candidate.py').read_text();req("env['BUSINESSOS_WORKSPACE']=str(run['workspace'])" in runner,'candidate runner must pin every AURA helper to the staged organization workspace');req('candidate-attempts' in runner and 'stderr=subprocess.STDOUT' in runner and 'shutil.copy2' in runner,'candidate runner must preserve attempts while promoting only successful candidate-visible output for review');req("blocker_classification='external_capability'" not in runner and 'task remains in progress with its original before-checkpoint' in runner.lower() and 'raise SystemExit(code)' in runner,'candidate-process failure must remain a recoverable execution interruption rather than becoming a semantic blocker or silent batch success');req('prepare a fresh run for a clean retry' not in runner,'candidate runner must allow same-run recovery after an execution interruption')
    judge_runner=(ROOT/'qualification/run_judge.py').read_text();req("PROMPT_TOKEN='{judge_prompt}'" in judge_runner and 'exactly this qualification run' in judge_runner,'judge runner must bind professional review to one explicit evaluator run');req('judgment event IDs do not match this run' in judge_runner and "set(actual)!=set(expected)" in judge_runner,'judge runner must reject stale or wrong-run judgments');req('candidate_surface_root' in judge_runner and 'review-packets-to-judge.json' in judge_runner,'judge runner must expose only the current run evidence surfaces needed for review')
    print('qualification integrity regressions passed: realistic cases and focused diagnostics only; deterministic honesty stays small; capable review owns semantic quality')

if __name__=='__main__':main()
