from _common import installed_modules

# AURA business areas organize operating knowledge. They are not execution services and
# do not imply that every request needs a Playbook.
OPERATING_AREAS = {
    'competitor-intelligence': {'title':'Competitive Intelligence','summary':'Understand competitors, substitutes, competitive movement, and supported implications.'},
    'customer-intelligence': {'title':'Customer Intelligence','summary':'Understand customers, prospects, needs, language, decisions, and experiences from appropriate evidence.'},
    'industry-intelligence': {'title':'Industry Intelligence','summary':'Understand material external developments in the market, regulation, research, technology, and industry.'},
    'seo-aeo': {'title':'SEO/AEO','summary':'Improve valuable organic discovery across search, answer engines, AI interfaces, local discovery, and related surfaces.'},
    'content-synthesis': {'title':'Content Synthesis','summary':'Turn useful ideas, evidence, and source material into strong audience-appropriate content.'},
    'marketing-synthesis': {'title':'Marketing Synthesis','summary':'Create and improve persuasive strategy, campaigns, offers, and customer-facing marketing assets.'},
    'customer-optimization': {'title':'Customer Optimization','summary':'Improve the customer journey from qualification and purchase through value, retention, expansion, recovery, and referral.'},
}


def _p(id, owner_system, title, summary, example, entry_workflow=None, discovery_terms=()):
    return {
        'id': id,
        'owner_system': owner_system,
        'title': title,
        'summary': summary,
        'example': example,
        'entry_workflow': entry_workflow,
        'discovery_terms': list(discovery_terms),
    }


# Canonical Playbooks are explicit product knowledge. A Playbook must earn top-level status
# as a meaningful end-to-end business job; it is never inferred from Workflow metadata or
# generated build artifacts. Narrow variants and supporting procedures remain directly
# discoverable as Workflows.
PLAYBOOKS = [
    # Competitive Intelligence
    _p('competitor-research','competitor-intelligence','Competitor Research',
       'Identify the competitors and substitutes that matter, understand what they are doing, compare the business against them, and derive supported implications.',
       'Research our competitors and tell me what they are doing better than us.',
       'competitor.analysis.competitive-position',
       ('competitor research','competitive analysis','competitive landscape','competitors','competition','pricing comparison','positioning comparison','competitor ads','competitor content')),
    _p('competitor-monitoring','competitor-intelligence','Competitor Monitoring',
       'Keep important competitive movement current and distinguish observed changes from unsupported assumptions about effectiveness or intent.',
       'Tell me what materially changed with our competitors since we last looked.',
       'competitor.intelligence.ecosystem-radar',
       ('competitor monitoring','competitive monitoring','competitor changes','emerging competitors','competitive movement')),

    # Customer Intelligence
    _p('customer-research','customer-intelligence','Customer Research',
       'Resolve an important customer knowledge need with evidence appropriate to the decision, using the relevant research and analysis Workflows.',
       'Research our customers and tell me what they care about most.',
       'customer.research.plan',
       ('customer research','customer needs','customer interviews','surveys','reviews','decision drivers','customer problems','customer expectations')),
    _p('voice-of-customer','customer-intelligence','Voice of Customer',
       'Build reusable evidence-backed understanding of the language, pains, desires, objections, outcomes, and decision criteria customers actually express.',
       'Build a voice-of-customer view we can use in our product and marketing work.',
       'customer.analysis.voice-of-customer',
       ('voice of customer','voc','customer language','pains','desires','objections','jobs to be done','customer quotes')),

    # Industry Intelligence
    _p('industry-intelligence','industry-intelligence','Industry Intelligence',
       'Discover and evaluate material news, research, regulation, technology, market shifts, and other external changes that could affect the organization.',
       'What changed in our industry that actually matters to us?',
       'industry.intelligence.ecosystem-radar',
       ('industry research','industry intelligence','market research','news','regulation','research','technology change','market change','trends')),
    _p('industry-rapid-response','industry-intelligence','Industry Rapid Response',
       'Build a fast, evidence-backed understanding of a time-sensitive external development and its plausible business implications.',
       'This just happened in our industry. Figure out what it means for us.',
       'industry.analysis.rapid-response',
       ('breaking industry news','rapid response','industry event','urgent industry change','regulatory change')),

    # SEO/AEO
    _p('seo-aeo-growth','seo-aeo','SEO/AEO Growth',
       'Find and improve the highest-value realistic opportunities for organic discovery across search engines, answer engines, AI interfaces, and local discovery.',
       'Find our highest-value SEO/AEO opportunities and do the useful work to improve them.',
       None,
       ('seo','aeo','organic search','search rankings','organic traffic','local search','ai answers','answer engines','technical seo','content gap','search opportunity')),
    _p('seo-aeo-experimentation','seo-aeo','SEO/AEO Experimentation and Learning',
       'Test uncertain SEO/AEO tactics when testing is worthwhile, evaluate results without overstating causality, and preserve reusable Learning when supported.',
       'Test whether this SEO/AEO tactic actually helps us and learn from the result.',
       'seo.learning.strategy-experiment-design',
       ('seo experiment','aeo experiment','organic experiment','seo test','seo learning','measure seo change')),
    _p('seo-site-migration','seo-aeo','SEO/AEO Site Migration',
       'Plan and execute a domain, CMS, architecture, or URL migration while protecting organic discovery, attribution, and recoverability.',
       "We're migrating our site. Help us preserve SEO/AEO and catch migration problems.",
       'seo.execution.technical.site-migration',
       ('site migration','domain migration','cms migration','url migration','seo migration','redirect migration')),

    # Content Synthesis
    _p('content-strategy','content-synthesis','Content Strategy and Synthesis',
       'Turn audience context, evidence, ideas, performance signals, and communication goals into a strong content approach before or across specific formats.',
       'Figure out what content we should create and why, then turn the best ideas into useful work.',
       'content.intake.content-brief',
       ('content strategy','content plan','content ideas','content research','content performance','trending content','creator research')),
    _p('content-synthesis-animation','content-synthesis','Animation / Motion Production',
       'Use motion to explain change, sequence, causality, demonstration, or attention hierarchy.',
       'Create an animation or motion asset that explains this clearly.',
       'content.production.animation',
       ('animation','motion graphics','animated explainer','motion content','gif','looping motion')),
    _p('content-synthesis-article','content-synthesis','Article Production',
       'Produce a useful, evidence-backed article with appropriate depth, structure, and reader progression.',
       'Create the article we need for this topic and audience.',
       'content.production.article',
       ('article','blog post','written content','editorial content','long-form article')),
    _p('content-synthesis-audio','content-synthesis','Audio Asset Production',
       'Produce voiceover, narration, clip, or other audio asset optimized for its actual use context.',
       'Create the audio asset we need for this communication job.',
       'content.production.audio',
       ('audio asset','voiceover','narration','audio clip','spoken audio')),
    _p('content-synthesis-carousel','content-synthesis','Carousel / Slideshow Production',
       'Turn an idea into a sequential visual argument where each frame earns the next.',
       'Turn this idea into a strong carousel.',
       'content.production.carousel',
       ('carousel','social carousel','slideshow','sequential visual','slide post')),
    _p('content-synthesis-case-study','content-synthesis','Customer Case Study',
       'Turn verified customer evidence and ProofRecords into a useful, accurate account of context, intervention, mechanism, and outcome.',
       'Turn this verified customer result into a credible case study.',
       'content.production.case-study',
       ('case study','customer story','customer result','success story','proof asset')),
    _p('content-synthesis-demo','content-synthesis','Demonstration Asset Production',
       'Produce a clear, verifiable demonstration that visibly proves or teaches the intended mechanism, use case, or result.',
       'Create a demonstration that clearly shows how this works.',
       'content.production.demo',
       ('demo','demonstration','product demo','how it works','proof demonstration')),
    _p('content-synthesis-faq','content-synthesis','FAQ Content Production',
       'Create evidence-backed answers to recurring audience questions in a form that is easy to find and understand.',
       'Create a useful FAQ from the questions our audience actually has.',
       'content.production.faq',
       ('faq','frequently asked questions','customer questions','question answers','help content')),
    _p('content-synthesis-image','content-synthesis','Image / Graphic Production',
       'Create a visual asset whose composition communicates the intended idea rather than adding decoration.',
       'Create the image or graphic we need to communicate this idea.',
       'content.production.image',
       ('image','graphic','visual asset','social graphic','illustration')),
    _p('content-synthesis-infographic','content-synthesis','Infographic Production',
       'Turn evidence or a structured idea into a clear visual explanation whose information hierarchy works even when the viewer only scans it.',
       'Turn this evidence into a clear infographic.',
       'content.production.infographic',
       ('infographic','data graphic','visual explanation','information design')),
    _p('content-synthesis-long-video','content-synthesis','Long-Form Video Production',
       'Create sustained video communication with narrative or educational progression, demonstrations, and retention-aware structure.',
       'Create the long-form video we need for this subject.',
       'content.production.long-video',
       ('long-form video','youtube video','educational video','video essay','long video')),
    _p('content-synthesis-newsletter','content-synthesis','Newsletter Production',
       'Create a relationship-oriented email or newsletter suited to inbox context and the audience expectation.',
       'Create this edition of our newsletter.',
       'content.production.newsletter',
       ('newsletter','email newsletter','editorial email','subscriber email')),
    _p('content-synthesis-podcast','content-synthesis','Podcast Episode Production',
       'Create an audio-first episode whose structure and delivery fit listening context.',
       'Create the podcast episode we need for this topic.',
       'content.production.podcast',
       ('podcast','podcast episode','audio show','interview episode','audio-first content')),
    _p('content-synthesis-presentation','content-synthesis','Presentation / Slideshow Production',
       'Build a presentation that supports a live or asynchronous audience journey instead of turning a document into slides.',
       'Build the presentation we need for this audience and objective.',
       'content.production.presentation',
       ('presentation','slide deck','slideshow','webinar slides','meeting deck')),
    _p('content-synthesis-short-video','content-synthesis','Short-Form Video Production',
       'Express one useful idea quickly through platform-native visual and audio pacing and proof.',
       'Create a short-form video that communicates this idea effectively.',
       'content.production.short-video',
       ('short-form video','short video','reel','tiktok','youtube short','social video')),
    _p('content-repurposing-adaptation','content-synthesis','Content Repurposing & Adaptation',
       'Turn a validated core asset or idea into the smallest useful set of derivative and platform-native assets without unnecessary variants or distorted meaning.',
       'Turn this core asset into the useful derivative content we should actually publish.',
       None,
       ('content repurposing','repurpose content','content adaptation','platform adaptation','clips','derivative assets','linkedin content','captions','thumbnail')),

    # Marketing Synthesis
    _p('marketing-strategy','marketing-synthesis','Marketing Strategy and Messaging',
       'Develop or improve positioning, messaging, value proposition, mechanism, proof, objection handling, and offer presentation around current customer and business truth.',
       'Improve how we position and explain this offer so qualified buyers understand why it matters.',
       'marketing.strategy.messaging',
       ('marketing strategy','positioning','messaging','value proposition','mechanism','proof','objections','offer presentation')),
    _p('campaign-development','marketing-synthesis','Campaign Development',
       'Build a coherent campaign concept and the useful persuasive work needed to carry it across the relevant customer-facing surfaces.',
       'Build a campaign around our strongest customer insight and offer.',
       'marketing.campaigns.campaign-concept',
       ('campaign','campaign strategy','campaign concept','marketing campaign','launch campaign')),
    _p('offer-design-optimization','marketing-synthesis','Offer Design & Optimization',
       'Diagnose and improve how value is packaged, priced, de-risked, and presented so the offer is more compelling without inventing unsupported value or urgency.',
       'Improve the offer itself, not just the copy around it.',
       'marketing.offer.diagnosis',
       ('offer design','offer optimization','offer packaging','pricing','guarantee','risk reversal','bonuses','offer terms')),
    _p('marketing-synthesis-ads','marketing-synthesis','Advertising Creative & Copy',
       'Create persuasive ad concepts, copy, and creative requirements matched to audience, awareness, journey role, placement context, evidence, and destination.',
       'Create the advertising creative and copy we need for this campaign.',
       'marketing.assets.ads',
       ('ads','advertising','ad creative','ad copy','paid social creative','paid search creative')),
    _p('marketing-synthesis-advertorial','marketing-synthesis','Advertorial',
       'Create clearly compliant editorial-style persuasion that educates while transparently serving a commercial objective.',
       'Create a transparent advertorial for this offer and audience.',
       'marketing.assets.advertorial',
       ('advertorial','native advertising','editorial advertising','sponsored article')),
    _p('marketing-synthesis-email-sequence','marketing-synthesis','Commercial Email Sequence',
       'Design a multi-email persuasion sequence where each message has a distinct job and builds appropriately on prior context.',
       'Create the commercial email sequence we need for this audience and offer.',
       'marketing.assets.email-sequence',
       ('email sequence','sales emails','commercial email','launch emails','promotional email sequence')),
    _p('marketing-synthesis-comparison','marketing-synthesis','Comparison & Alternative Persuasion',
       'Help qualified buyers evaluate alternatives honestly using customer decision criteria and current competitive evidence.',
       'Create an honest comparison that helps qualified buyers evaluate their options.',
       'marketing.assets.comparison',
       ('comparison page','alternatives page','versus page','competitor comparison','buyer comparison')),
    _p('marketing-synthesis-landing-page','marketing-synthesis','Landing Page Persuasion',
       'Create a landing page or homepage that continues acquisition intent and moves the right visitor toward the desired action without overstating business truth.',
       'Create or improve this landing page so qualified visitors understand and act.',
       'marketing.assets.landing-page',
       ('landing page','homepage copy','conversion page','sales page','lead page')),
    _p('marketing-synthesis-lead-magnet','marketing-synthesis','Lead Magnet',
       'Create an exchange-worthy asset that solves a bounded valuable problem and naturally relates to the next commercial step.',
       'Create a lead magnet worth exchanging contact information for.',
       'marketing.assets.lead-magnet',
       ('lead magnet','download','guide','checklist','template','lead generation asset')),
    _p('marketing-synthesis-nurture','marketing-synthesis','Lead Nurture Strategy',
       'Move not-yet-ready prospects toward a better-informed decision over time rather than repeatedly asking for the sale.',
       'Build a nurture approach for prospects who are interested but not ready to buy.',
       'marketing.assets.nurture',
       ('lead nurture','nurture strategy','nurture campaign','prospect education','lifecycle nurture')),
    _p('marketing-synthesis-quiz-assessment','marketing-synthesis','Quiz / Assessment Conversion Asset',
       'Create a diagnostic experience that gives the participant useful feedback while qualifying or segmenting toward a relevant next action.',
       'Create a useful assessment that also helps us qualify the right next step.',
       'marketing.assets.quiz-assessment',
       ('quiz','assessment','diagnostic','interactive assessment','lead qualification quiz')),
    _p('marketing-synthesis-sales-enablement','marketing-synthesis','Sales Enablement Asset',
       'Create persuasive evidence and tools that help sellers and buyers resolve real decision questions consistently.',
       'Create the sales enablement asset our team needs for this buyer decision.',
       'marketing.assets.sales-enablement',
       ('sales enablement','battlecard','sales one-pager','buyer enablement','sales collateral')),
    _p('marketing-synthesis-sales-letter','marketing-synthesis','Sales Letter',
       'Create long-form written persuasion appropriate to audience sophistication and offer complexity.',
       'Create a sales letter for this offer and audience.',
       'marketing.assets.sales-letter',
       ('sales letter','long-form sales copy','direct response letter','long-form persuasion')),
    _p('marketing-synthesis-vsl','marketing-synthesis','Video Sales Letter',
       'Build a sustained video persuasion narrative tied to an Offer and measurable commercial action.',
       'Create the VSL we need for this offer.',
       'marketing.assets.vsl',
       ('vsl','video sales letter','sales video','video persuasion')),
    _p('marketing-synthesis-webinar','marketing-synthesis','Webinar Persuasion',
       'Design a webinar that creates genuine understanding and value while logically leading qualified attendees to an Offer.',
       'Build a useful webinar that naturally leads qualified attendees to our offer.',
       'marketing.assets.webinar',
       ('webinar','webinar funnel','webinar presentation','webinar marketing','commercial webinar')),

    # Customer Optimization
    _p('customer-journey-optimization','customer-optimization','Customer Journey Optimization',
       'Understand the journey, identify the most important progression problem, diagnose the likely cause, improve it, and evaluate what changed.',
       'Figure out where customers are getting stuck and improve the most important part of the journey.',
       'customer-optimization.diagnosis.bottleneck-prioritization',
       ('customer journey','journey optimization','funnel optimization','bottleneck','drop off','conversion','customer experience')),
    _p('retention-and-churn','customer-optimization','Retention and Churn',
       'Understand why customers leave or fail to realize value, improve the relevant experience, and evaluate durable retention rather than manipulating short-term staying behavior.',
       'Figure out why customers are churning and what we should improve.',
       'customer-optimization.intervention.retention',
       ('retention','churn','renewal','customer success','activation','adoption','time to value')),
]


def all_playbooks(registry=None):
    # Generators already pass a registry; Playbook identity intentionally does not depend on it.
    return [dict(row) for row in PLAYBOOKS]


def installed_playbooks(registry=None):
    installed = installed_modules()
    return [row for row in all_playbooks(registry) if row['owner_system'] in installed]


def playbooks_for_system(owner_system, registry=None):
    return [row for row in installed_playbooks(registry) if row['owner_system'] == owner_system]


def get_playbook(playbook_id, registry=None):
    return next((row for row in installed_playbooks(registry) if row['id'] == playbook_id), None)
