#!/usr/bin/env python3
from _common import *
from run_provenance import RUN_BOUND_TYPES, LEGACY_ORIGINS
from completion_evidence import qa_record_ok, subcontract_manifest_errors, validate_evidence
import json

CUSTOMER_FACING_ROLE='customer_facing_production_root'
INTERNAL_MARKETING_ROLES={'internal_brief','internal_strategy','internal_analysis','internal_research','internal_planning'}

def _contract_index():
    try:return {c['id']:c for c in load_registry().get('contracts',[]) if c.get('id')}
    except Exception:return {}


def _generic_run_errors(business_id,objects,contracts,active_run_id=None):
    """Require execution-significant canonical state to be bound to real completed Run evidence."""
    errors=[]
    for obj,path in objects:
        typ=obj.get('object_type')
        if typ not in RUN_BOUND_TYPES:continue
        ext=obj.get('extensions') if isinstance(obj.get('extensions'),dict) else {}
        bos=ext.get('businessos') if isinstance(ext.get('businessos'),dict) else {}
        origin=bos.get('origin');rr=bos.get('run_ref')
        if origin in LEGACY_ORIGINS:
            if rr:errors.append(f'{path} {typ} cannot combine origin={origin!r} with extensions.businessos.run_ref; imported/preexisting means the object predates the producing Run rather than being generated by it')
            continue
        if not rr:
            errors.append(f'{path} {typ} requires extensions.businessos.run_ref to auditable bounded Run evidence; only explicitly imported/preexisting state is exempt');continue
        d=ROOT/rr
        if not d.exists() or not d.is_dir():errors.append(f'{path} {typ} run_ref does not resolve to a Run directory: {rr}');continue
        mp=d/'contract-execution.json';rp=d/'run.json'
        if not mp.exists() or not rp.exists():errors.append(f'{path} {typ} Run lacks run.json/contract-execution.json: {rr}');continue
        try:m=json.loads(mp.read_text());r=json.loads(rp.read_text())
        except Exception as e:errors.append(f'{path} {typ} invalid Run state: {e}');continue
        if m.get('business_id')!=business_id or r.get('business_id')!=business_id:errors.append(f'{path} {typ} Run business_id mismatch: {rr}')
        rid=r.get('run_id')
        if bos.get('run_id') and bos.get('run_id')!=rid:errors.append(f'{path} {typ} extensions.businessos.run_id does not match referenced Run: {bos.get("run_id")!r} vs {rid!r}')
        root_id=m.get('root_contract_id')
        if not root_id or r.get('contract_id')!=root_id:errors.append(f'{path} {typ} Run root contract mismatch between run.json and contract-execution.json: {rr}')
        root=contracts.get(root_id)
        if not root:errors.append(f'{path} {typ} Run root contract is missing from the installed registry: {root_id!r}')
        else:
            owner=obj.get('owner_system');root_owner=root.get('owner_system')
            if owner and root_owner not in {None,'core',owner}:errors.append(f'{path} {typ} owner_system does not match producing Run root contract owner: {owner} vs {root_owner}')
        if bos.get('run_contract_id') and bos.get('run_contract_id')!=root_id:errors.append(f'{path} {typ} extensions.businessos.run_contract_id does not match Run root contract: {bos.get("run_contract_id")!r} vs {root_id!r}')
        expected_active=bool(active_run_id and rid==active_run_id and m.get('root_status')=='active' and r.get('status')=='active')
        if not expected_active and (m.get('root_status')!='completed' or r.get('status')!='completed'):errors.append(f'{path} {typ} references a Run that is not completed: {rr}')
        evidence=set(m.get('root_evidence_refs') or [])
        for step in (m.get('contracts') or {}).values():evidence.update(step.get('evidence_refs') or [])
        norm=str(Path(path))
        if not expected_active and norm not in {str(Path(x)) for x in evidence}:errors.append(f'{path} {typ} is not recorded as completion evidence by its referenced Run: {rr}')
    return errors


def _semantic_run_errors(business_id,objects,contracts):
    """Re-check completion profiles so hand-editing a manifest cannot bypass complete_run.py."""
    errors=[];seen=set()
    for obj,_ in objects:
        ext=obj.get('extensions') if isinstance(obj.get('extensions'),dict) else {}
        bos=ext.get('businessos') if isinstance(ext.get('businessos'),dict) else {}
        if bos.get('origin') in LEGACY_ORIGINS:continue
        rr=bos.get('run_ref')
        if not rr or rr in seen:continue
        seen.add(rr);d=ROOT/rr;mp=d/'contract-execution.json';rp=d/'run.json'
        if not mp.exists() or not rp.exists():continue
        try:m=json.loads(mp.read_text());r=json.loads(rp.read_text())
        except Exception:continue
        if m.get('root_status')!='completed' or r.get('status')!='completed':continue
        root_id=m.get('root_contract_id');root=contracts.get(root_id);rid=r.get('run_id')
        if not root or not rid:continue
        sem=validate_evidence(root,m.get('root_evidence_refs') or [],business_id,rid,phase='root',manifest=m)
        errors.extend(f'{rr} completion evidence invalid for {root_id}: {e}' for e in sem)
        sub=subcontract_manifest_errors(m,business_id,rid,contracts)
        errors.extend(f'{rr} required subcontract evidence invalid: {e}' for e in sub)
    return errors


def run_completion_errors(business_id,objects,active_run_id=None):
    errors=[];contracts=_contract_index()
    errors.extend(_generic_run_errors(business_id,objects,contracts,active_run_id))
    errors.extend(_semantic_run_errors(business_id,objects,contracts))
    for asset,path in objects:
        if asset.get('object_type')!='Asset' or asset.get('owner_system') not in {'content-synthesis','marketing-synthesis'}:continue
        bos=(asset.get('extensions') or {}).get('businessos',{}) if isinstance(asset.get('extensions'),dict) else {}
        customer_facing=bos.get('customer_facing', True);rr=bos.get('run_ref');origin=bos.get('origin')
        if origin in {'imported','preexisting'} and rr:errors.append(f'{path} Asset cannot combine origin={origin!r} with run_ref; a draft generated in the current execution is Run-produced even when unpublished')
        if asset.get('owner_system')=='marketing-synthesis' and customer_facing is False:
            role=str(asset.get('business_role') or '').strip().lower()
            if role not in INTERNAL_MARKETING_ROLES:errors.append(f'{path} marketing-synthesis Asset may set customer_facing=false only for an explicitly internal support role ({", ".join(sorted(INTERNAL_MARKETING_ROLES))}); an unpublished homepage/landing-page/email/ad/etc. draft remains customer-facing by intended use')
        if not rr:
            if origin not in {'imported','preexisting'}:errors.append(f'{path} Content/Marketing Asset requires extensions.businessos.run_ref for auditable production; imported/preexisting Assets must explicitly mark origin')
            continue
        d=ROOT/rr
        if not d.exists() or not d.is_dir():errors.append(f'{path} Asset run_ref does not resolve to a Run directory: {rr}');continue
        mp=d/'contract-execution.json';rp=d/'run.json'
        if not mp.exists() or not rp.exists():errors.append(f'{path} production Asset Run lacks auditable contract-execution manifest: {rr}');continue
        try:m=json.loads(mp.read_text());r=json.loads(rp.read_text())
        except Exception as e:errors.append(f'{path} invalid Run completion state: {e}');continue
        expected_active=bool(active_run_id and r.get('run_id')==active_run_id and m.get('root_status')=='active' and r.get('status')=='active')
        if m.get('business_id')!=business_id or r.get('business_id')!=business_id:errors.append(f'{path} Run business_id mismatch: {rr}')
        root_id=m.get('root_contract_id')
        if not root_id or r.get('contract_id')!=root_id:errors.append(f'{path} Run root contract mismatch between run.json and contract-execution.json: {rr}')
        root=contracts.get(root_id)
        if not root:errors.append(f'{path} Run root contract is missing from the installed contract registry: {root_id!r}')
        else:
            if root.get('owner_system')!=asset.get('owner_system'):errors.append(f'{path} Asset owner_system does not match producing Run root contract owner: {asset.get("owner_system")} vs {root.get("owner_system")}')
            if root.get('artifact_role')==CUSTOMER_FACING_ROLE and customer_facing is False:errors.append(f'{path} Asset produced under customer-facing production root {root_id!r} cannot opt out with customer_facing=false; draft/publication status does not change intended audience')
            if customer_facing is not False and root.get('artifact_role')!=CUSTOMER_FACING_ROLE:errors.append(f'{path} customer-facing Asset must reference a Run whose root contract is marked artifact_role={CUSTOMER_FACING_ROLE}; got {root_id!r}')
        required=m.get('required_subcontracts',[]);steps=m.get('contracts',{})
        for cid in required:
            st=steps.get(cid,{})
            if st.get('status')!='completed' and not expected_active:errors.append(f'{path} required subcontract not completed for Asset Run: {cid}')
            refs=st.get('evidence_refs') or []
            if not refs and (st.get('status')=='completed' or not expected_active):errors.append(f'{path} completed subcontract lacks evidence refs: {cid}')
            for rel in refs:
                if not resolve_storage_ref(rel).exists():errors.append(f'{path} subcontract evidence ref missing: {cid} -> {rel}')
            if ('.qa' in cid or cid.endswith('.qa')) and (st.get('status')=='completed' or not expected_active) and not qa_record_ok(cid,refs,business_id,r.get('run_id')):errors.append(f'{path} QA subcontract lacks structured matching JSON pass evidence: {cid}')
        if not expected_active and (m.get('root_status')!='completed' or r.get('status')!='completed'):errors.append(f'{path} production Asset references a Run that is not completed: {rr}')
        root_refs=m.get('root_evidence_refs') or []
        if not root_refs and not expected_active:errors.append(f'{path} completed production Run lacks root deliverable evidence: {rr}')
        for rel in root_refs:
            if not resolve_storage_ref(rel).exists():errors.append(f'{path} root completion evidence ref missing: {rel}')
        loc=asset.get('location_reference')
        if customer_facing is not False and loc:
            locrel=storage_ref(resolve_storage_ref(loc));refnorm={str(Path(x)) for x in root_refs}
            if not expected_active and str(Path(locrel)) not in refnorm:errors.append(f'{path} completed production Run root evidence does not include the customer-facing Asset file: {locrel}')
        chain=bos.get('contract_chain')
        if not isinstance(chain,list):errors.append(f'{path} production Asset requires extensions.businessos.contract_chain including the root and required subcontracts')
        else:
            if root_id and root_id not in chain:errors.append(f'{path} Asset contract_chain omits producing root contract: {root_id}')
            missing=[x for x in required if x not in chain]
            if missing:errors.append(f'{path} Asset contract_chain omits required subcontract(s): {", ".join(missing)}')
    return errors
